### ISSUE TITLE
deer-listening event scope

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#38]
I have a list item like
```html
<li deer-id="http://devstore.rerum.io/v1/id/5df7d0e3e4b0a6b3a238ebd3">Hello World<a onclick="doSomething()">Click Me</a></li>
```

I am `deer-listening` to the `<ul>` containing the items.  When I click toSomething(), that something happens, but the listener also builds out `http://devstore.rerum.io/v1/id/5df7d0e3e4b0a6b3a238ebd3`in the element that is listening.  

This is especially problematic for removing items from collections, since when I click to remove it, it both loads its template in the element listening and removes the item from the list, an action over which as a 3rd party developer I seem to have no control over.  We need to dug into deer-listening a bit to scope out events in these scenarios.

**Comment by cubap** [comment]
This is the expected behavior of event listeners, here. If the delete does not want other things to fire, it should event.preventDefault() or stopPropogation or Bubbles=false or whatever it's called. Since the delete button is the most specific element, it will fire first and can prevent anything else from happening. If there is an event on the item itself, there may be a tug-o-war, but I can't think of something offhand that breaks because of that.
________________________________

**Comment by thehabes** [comment]
Oh we have already thought of this.  `LR.utils.removeCollectionEntry()` broadcasts `lrCollectionItemDeleted`.  We need to listen for that event on any page where a delete could happen then tell that listener to event.preventDefault() or stopPropogation or Bubbles=false or whatever it's called, ensuring the other click listeners do not fire.

**Comment by thehabes** [comment]
This is a Lived Religion issue, not a DEER issue, since lived religion handles the templates and functionality that are doing this.
