### ISSUE TITLE
deer-updated MUST be broadcasted

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/deer#40]
Although we can talk about exactly where.  However, right now, this is never broadcasted, so it can't be detected by 3rd party apps.

**Comment by thehabes** [comment]
Also see #34

**Comment by cubap** [comment]
Two parts:

We need an `ANNOTATION-UPDATED` Event that carries the most effective note of the item changed. This may update form inputs or rendered templates. On the receiving end, there should be an automatic watch on rendered templates that scries on these Events for their `deer-id` (perhaps turn-offable with some `DEER-STATIC="true"` attribute) and updates based on the payload _without_ re`expand()`ing the original object.

**Comment by cubap** [comment]
#71 is related

**Comment by cubap** [comment]
We don't need `ANNOTATION-UPDATED` because `UPDATED` already does this, it just isn't used. There is a `Promise.all(annos)` around `deer-record.js:373` that should do the trick.

Listening for the Event and inspecting `event.detail.obj['@id']` for a match should work. As a help, we could upgrade the `@id` to `event.detail.uri` or something, if that is what is most needed.
